name: 'Subtree split'

on:
  push:
    branches:
      - 'main'
      - '[0-9].[0-9]'

jobs:
  subtree-split:
    name: 'Subtree split'
    runs-on: 'ubuntu-24.04'
    steps:
      - name: 'SSH Agent'
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.DEPLOY_KEY_SYMFONY_ADDON_CONSTRAINTS }}
            ${{ secrets.DEPLOY_KEY_SYMFONY_ADDON_FORM_TYPES }}
            ${{ secrets.DEPLOY_KEY_SYMFONY_ADDON_TRANSFORMERS }}
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: 'Git remote add'
        run: |
          git remote add symfony-addon-constraints git@github.com:darkwebdesign/symfony-addon-constraints.git
          git remote add symfony-addon-form-types git@github.com:darkwebdesign/symfony-addon-form-types.git
          git remote add symfony-addon-transformers git@github.com:darkwebdesign/symfony-addon-transformers.git
      - name: 'Git subtree split'
        run: |
          git subtree split --prefix=symfony-addon-constraints --branch symfony-addon-constraints
          git subtree split --prefix=symfony-addon-form-types --branch symfony-addon-form-types
          git subtree split --prefix=symfony-addon-transformers --branch symfony-addon-transformers
      - name: 'Git push'
        run: |
          git push symfony-addon-constraints "symfony-addon-constraints:${GITHUB_REF#refs/heads/}"
          git push symfony-addon-form-types "symfony-addon-form-types:${GITHUB_REF#refs/heads/}"
          git push symfony-addon-transformers "symfony-addon-transformers:${GITHUB_REF#refs/heads/}"
